debug_noisy:
	g++ -g -o allele_counter allele_counter.cpp allele_counter_convert.cpp allele_counter_extract.cpp read_extract_bg_qref.cpp read_extract_cons.cpp convert_shore_pileup.cpp globals.cpp precheck_opt.cpp print_allele_count.cpp print_error_exit.cpp read_allele_count2.cpp read_chromosomes.cpp read_marker.cpp split_string.cpp is_number.cpp
	cp allele_counter ../dev_bin
